# Generated by Django 5.0.7 on 2024-07-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Kompaniya', 'verbose_name_plural': 'Kompaniyalar'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Xaridorlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Savdo', 'verbose_name_plural': 'Savdolar'},
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.company', verbose_name='Kompaniya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Mahsulot soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.company', verbose_name='Kompaniya'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.customer', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(verbose_name='Sotilgan soni'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan vaqti'),
        ),
    ]
